import random


def gen():
    num = random.randrange(100, 999)
    l2 = list()
    for j in range(3):
        l2.append(num % 10)
        num = num // 10
    l2.reverse()
    return l2


print("Welcome to the Number Breaker!")
print("Guess the number generated by the computer. You will get clues after every guess.")
numArr = gen()


def wincheck(l):
    flag = True
    for z in range(3):
        if l[z] != numArr[z]:
            flag = False
    return flag


while True:
    guess = int(input("Make a guess: "))
    match = False
    same = False
    none = False
    l1 = list()
    for i in range(3):
        l1.append(guess % 10)
        guess = guess // 10
    l1.reverse()

    for x in range(3):
        for y in range(3):
            if l1[y] == numArr[x] and x == y and match == False:
                match = True

            if l1[y] == numArr[x] and x != y and same == False:
                same = True

            if l1[y] != numArr[x] and x != y and none == False:
                none = True

    if match == True:
        score = wincheck(l1)
        if score == True:
            print("You guessed the number correctly!")
            break
        print("Match - A digit matches and is placed correctly!")
    elif match == False and same == True:
        print("Same - A digit matches but is placed incorrectly")
    else:
        print("None - Nothing matches. Please guess again.")
